### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by jerkjerk21** [stephanlensky/hyacinth#75]
So I'm trying to run Hyacinth and while I was running the command: docker-compose up service, I keep getting this message below.

service-1  | FileNotFoundError: Could not find local geospatial data. Please download gadm36_USA.gpkg and cities1000.txt to use local geocoding.
service-1  | error: Recipe `run` failed on line 37 with exit code 1

I live in Canada so I don't know if it'll have to be changed and I haven't messed around with any of the files.

**Comment by stephanlensky** [comment]
👋 Hi, these docs should explain what you need to do: https://slensky.com/hyacinth/getting-started/#downloading-geocoding-data

At the moment, only the US is supported for the local geocoding method, so since you are in Canada you'll need to use the Google geocoding API. Some information about how to get a key is available here if you are interested https://developers.google.com/maps/documentation/geocoding/cloud-setup

**Comment by jerkjerk21** [comment]
> 👋 Hi, these docs should explain what you need to do: https://slensky.com/hyacinth/getting-started/#downloading-geocoding-data
> 
> At the moment, only the US is supported for the local geocoding method, so since you are in Canada you'll need to use the Google geocoding API. Some information about how to get a key is available here if you are interested, but be aware that configuring a project and setting up billing/budget is a somewhat involved process. https://developers.google.com/maps/documentation/geocoding/cloud-setup

H
