### ISSUE TITLE
"Could not find product JSON in product data script" change in html structure?

### ISSUE THREAD

**Issue by JrVega03** [stephanlensky/hyacinth#84]
Keep getting this error, any advice what might be the culprit?
```
service-1  | Traceback (most recent call last):
service-1  |   File "/app/plugins/marketplace/client.py", line 159, in _parse_result_details
service-1  |     raise ValueError("Could not find product JSON in product data script")
service-1  | ValueError: Could not find product JSON in product data script
service-1  | 
service-1  | The above exception was the direct cause of the following exception:
service-1  | 
service-1  | Traceback (most recent call last):
service-1  |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
service-1  |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
service-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
service-1  |     return await get_listings(search_params, after_time, limit)
service-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 27, in get_listings
service-1  |     async for listing in search:
service-1  |   File "/app/plugins/marketplace/client.py", line 65, in _search
service-1  |     listing = _parse_result_details(url, result_content)
service-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service-1  |   File "/app/plugins/marketplace/client.py", line 185, in _parse_result_details
service-1  |     raise ParseError("Error parsing result details", content) from e
service-1  | hyacinth.exceptions.ParseError: Error parsing result details
service-1  | 2024-06-10 00:25:53 [9] [INFO] hyacinth.util.crash_report Saving error report to logs/poll_failure_2024-06-10T00:25:53.958917.txt
```

**Comment by aelharda** [comment]
getting the same error, I'm guessing Facebook changed their html structure.
`2024-06-11 01:52:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:52:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:53:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:53:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:54:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:54:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:55:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:55:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:56:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:56:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:57:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:57:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:58:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:58:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 01:59:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 01:59:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 02:00:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 02:00:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 02:01:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
service_1      | 2024-06-11 02:01:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
service_1      | 2024-06-11 02:01:48 [9] [DEBUG] hyacinth.monitor Polling search SearchSpec(id=1, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='108232089197273' category='vehicles') since 2024-06-10 20:01:48.776998+00:00
service_1      | 2024-06-11 02:01:49 [9] [DEBUG] plugins.marketplace.client Loading marketplace search results
service_1      | 2024-06-11 02:01:49 [9] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/108232089197273/vehicles/?sortBy=creation_time_descend&exact=false
service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Marketplace search results rendered
service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Getting search results page content
service_1      | Executing <Task pending name='Task-205' coro=<run_coroutine_job() running at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/base_py3.py:30> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:448> cb=[AsyncIOExecutor._do_submit_job.<locals>.callback() at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/asyncio.py:35, ProtocolCallback.__init__.<locals>.cb() at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py:195] created at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/asyncio.py:46> took 0.412 seconds
service_1      | 2024-06-11 02:01:54 [9] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/item/1010946653969312/
service_1      | 2024-06-11 02:01:58 [9] [DEBUG] plugins.marketplace.client Getting page content for https://www.facebook.com/marketplace/item/1010946653969312/
service_1      | 2024-06-11 02:01:59 [9] [ERROR] hyacinth.monitor Error polling search SearchSpec(id=1, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='108232089197273' category='vehicles')
service_1      | Traceback (most recent call last):
service_1      |   File "/app/plugins/marketplace/client.py", line 159, in _parse_result_details
service_1      |     raise ValueError("Could not find product JSON in product data script")
service_1      | ValueError: Could not find product JSON in product data script
service_1      | The above exception was the direct cause of the following exception:
service_1      | Traceback (most recent call last):
service_1      |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
service_1      |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
service_1      |     return await get_listings(search_params, after_time, limit)
service_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/client.py", line 27, in get_listings
service_1      |     async for listing in search:
service_1      |   File "/app/plugins/marketplace/client.py", line 65, in _search
service_1      |     listing = _parse_result_details(url, result_content)
service_1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/client.py", line 185, in _parse_result_details
service_1      |     raise ParseError("Error parsing result details", content) from e
service_1      | hyacinth.exceptions.ParseError: Error parsing result details
service_1      | 2024-06-11 02:01:59 [9] [INFO] hyacinth.util.crash_report Saving error report to logs/poll_failure_2024-06-11T02:01:59.105758.txt
service_1      | Job "SearchMonitor.poll_search (trigger: interval[0:10:00], next run at: 2024-06-11 02:11:48 UTC)" raised an exception
service_1      | Traceback (most recent call last):
service_1      |   File "/app/plugins/marketplace/client.py", line 159, in _parse_result_details
service_1      |     raise ValueError("Could not find product JSON in product data script")
service_1      | ValueError: Could not find product JSON in product data script
service_1      | The above exception was the direct cause of the following exception:
service_1      | Traceback (most recent call last):
service_1      |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
service_1      |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
service_1      |     return await get_listings(search_params, after_time, limit)
service_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/client.py", line 27, in get_listings
service_1      |     async for listing in search:
service_1      |   File "/app/plugins/marketplace/client.py", line 65, in _search
service_1      |     listing = _parse_result_details(url, result_content)
service_1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/plugins/marketplace/client.py", line 185, in _parse_result_details
service_1      |     raise ParseError("Error parsing result details", content) from e
service_1      | hyacinth.exceptions.ParseError: Error parsing result details
service_1      | During handling of the above exception, another exception occurred:
service_1      | Traceback (most recent call last):
service_1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
service_1      |     retval = await job.func(*job.args, **job.kwargs)
service_1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/hyacinth/monitor.py", line 82, in poll_search
service_1      |     listings = await self.__safe_poll_search(search_spec, after_time)
service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
service_1      |   File "/app/hyacinth/monitor.py", line 98, in __safe_poll_search
service_1      |     save_poll_failure_report(e)
service_1      |   File "/app/hyacinth/util/crash_report.py", line 24, in save_poll_failure_report
service_1      |     fname.parent.mkdir(parents=True, exist_ok=True)
service_1      |   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
service_1      |     os.mkdir(self, mode)`

**Comment by JrVega03** [comment]
> getting the same error, I'm guessing Facebook changed their html structure.
> 
> ```
> 2024-06-11 01:52:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:52:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:53:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:53:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:54:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:54:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:55:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:55:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:56:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:56:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:57:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:57:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:58:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:58:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 01:59:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 01:59:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 02:00:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 02:00:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 02:01:06 [9] [DEBUG] hyacinth.notifier Running notifier for new listings!
> service_1      | 2024-06-11 02:01:06 [9] [DEBUG] hyacinth.notifier Found 0 to notify for across 1 active searches
> service_1      | 2024-06-11 02:01:48 [9] [DEBUG] hyacinth.monitor Polling search SearchSpec(id=1, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='108232089197273' category='vehicles') since 2024-06-10 20:01:48.776998+00:00
> service_1      | 2024-06-11 02:01:49 [9] [DEBUG] plugins.marketplace.client Loading marketplace search results
> service_1      | 2024-06-11 02:01:49 [9] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/108232089197273/vehicles/?sortBy=creation_time_descend&exact=false
> service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Waiting for marketplace search results to render
> service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Marketplace search results rendered
> service_1      | 2024-06-11 02:01:53 [9] [DEBUG] plugins.marketplace.client Getting search results page content
> service_1      | Executing <Task pending name='Task-205' coro=<run_coroutine_job() running at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/base_py3.py:30> wait_for=<Future pending cb=[Task.task_wakeup()] created at /usr/local/lib/python3.12/asyncio/base_events.py:448> cb=[AsyncIOExecutor._do_submit_job.<locals>.callback() at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/asyncio.py:35, ProtocolCallback.__init__.<locals>.cb() at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/playwright/_impl/_connection.py:195] created at /home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/asyncio.py:46> took 0.412 seconds
> service_1      | 2024-06-11 02:01:54 [9] [DEBUG] hyacinth.util.scraping Navigating to page https://www.facebook.com/marketplace/item/1010946653969312/
> service_1      | 2024-06-11 02:01:58 [9] [DEBUG] plugins.marketplace.client Getting page content for https://www.facebook.com/marketplace/item/1010946653969312/
> service_1      | 2024-06-11 02:01:59 [9] [ERROR] hyacinth.monitor Error polling search SearchSpec(id=1, plugin_path=plugins.marketplace.plugin:MarketplacePlugin, search_params=location='108232089197273' category='vehicles')
> service_1      | Traceback (most recent call last):
> service_1      |   File "/app/plugins/marketplace/client.py", line 159, in _parse_result_details
> service_1      |     raise ValueError("Could not find product JSON in product data script")
> service_1      | ValueError: Could not find product JSON in product data script
> service_1      | The above exception was the direct cause of the following exception:
> service_1      | Traceback (most recent call last):
> service_1      |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
> service_1      |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
> service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
> service_1      |     return await get_listings(search_params, after_time, limit)
> service_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/client.py", line 27, in get_listings
> service_1      |     async for listing in search:
> service_1      |   File "/app/plugins/marketplace/client.py", line 65, in _search
> service_1      |     listing = _parse_result_details(url, result_content)
> service_1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/client.py", line 185, in _parse_result_details
> service_1      |     raise ParseError("Error parsing result details", content) from e
> service_1      | hyacinth.exceptions.ParseError: Error parsing result details
> service_1      | 2024-06-11 02:01:59 [9] [INFO] hyacinth.util.crash_report Saving error report to logs/poll_failure_2024-06-11T02:01:59.105758.txt
> service_1      | Job "SearchMonitor.poll_search (trigger: interval[0:10:00], next run at: 2024-06-11 02:11:48 UTC)" raised an exception
> service_1      | Traceback (most recent call last):
> service_1      |   File "/app/plugins/marketplace/client.py", line 159, in _parse_result_details
> service_1      |     raise ValueError("Could not find product JSON in product data script")
> service_1      | ValueError: Could not find product JSON in product data script
> service_1      | The above exception was the direct cause of the following exception:
> service_1      | Traceback (most recent call last):
> service_1      |   File "/app/hyacinth/monitor.py", line 95, in __safe_poll_search
> service_1      |     listings = await search_spec.plugin.get_listings(search_spec.search_params, after_time)
> service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/plugin.py", line 38, in get_listings
> service_1      |     return await get_listings(search_params, after_time, limit)
> service_1      |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/client.py", line 27, in get_listings
> service_1      |     async for listing in search:
> service_1      |   File "/app/plugins/marketplace/client.py", line 65, in _search
> service_1      |     listing = _parse_result_details(url, result_content)
> service_1      |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/plugins/marketplace/client.py", line 185, in _parse_result_details
> service_1      |     raise ParseError("Error parsing result details", content) from e
> service_1      | hyacinth.exceptions.ParseError: Error parsing result details
> service_1      | During handling of the above exception, another exception occurred:
> service_1      | Traceback (most recent call last):
> service_1      |   File "/home/joyvan/.cache/pypoetry/virtualenvs/hyacinth-9TtSrW0h-py3.12/lib/python3.12/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
> service_1      |     retval = await job.func(*job.args, **job.kwargs)
> service_1      |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/hyacinth/monitor.py", line 82, in poll_search
> service_1      |     listings = await self.__safe_poll_search(search_spec, after_time)
> service_1      |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> service_1      |   File "/app/hyacinth/monitor.py", line 98, in __safe_poll_search
> service_1      |     save_poll_failure_report(e)
> service_1      |   File "/app/hyacinth/util/crash_report.py", line 24, in save_poll_failure_report
> service_1      |     fname.parent.mkdir(parents=True, exist_ok=True)
> service_1      |   File "/usr/local/lib/python3.12/pathlib.py", line 1311, in mkdir
> service_1      |     os.mkdir(self, mode)
> ```

Glad i'm not the only one with this problem, i had suspicion it could be the html structure... hopefully this gets solved soon 👍

**Comment by aelharda** [comment]
@stephanlensky any help would be appreciated.

**Comment by Dshadows33** [comment]
I've been having the same issue for a couple of weeks now. I've done some digging myself and found this in the hyacinth > plugins > marketplace > client.py

`json_start = product_data_script.text.find('{"marketplace_product_details_page":')
        json_end = product_data_script.text.find(',"node":{', json_start)
        if json_start == -1 or json_end == -1:
            raise ValueError("Could not find product JSON in product data script")`
            
I've looked into one of the error pages and I can find marketplace_product_details_page in the page structure, but I can't find json_start. I'm not well versed in programing with the exception of R of all languages so I'm pretty lost on how to rectify the issue. If I had more time I could probably figure it out but I'm starting to fall behind on my school work and finals are two weeks from now. Hopefully @stephanlesky can help us out.

**Comment by Dshadows33** [comment]
"node" appears to be missing from what I can see from comparing the current structure from a html capture I did back in Febuary.

**Comment by Dshadows33** [comment]
There is also a new earlier instance of marketplace_product_details_page that is possibly screwing it up.

**Comment by stephanlensky** [comment]
👋 Appreciate all of the digging here, I agree it seems likely that Facebook changed their HTML and the previous method of extracting listing information will no longer work.

Hopefully I'll have some time in the next week or two to put up a fix.

**Comment by stephanlensky** [comment]
This should now be fixed. Try pulling latest and let me know if you still have any issues, thanks 🙂

**Comment by aelharda** [comment]
@JrVega03 @Dshadows33 can you confirm on your end that things are working? I rebuilt the project from scratch, but i don't get notified even though i know the listings are present. Also there is an error that keeps creeping up, logs attached.
[poll_failure_2024-06-14T03_51_13.241279.txt](https://github.com/user-attachments/files/15831361/poll_failure_2024-06-14T03_51_13.241279.txt)

**Comment by stephanlensky** [comment]
@aelharda that looks like a different issue, which we're tracking here https://github.com/stephanlensky/hyacinth/issues/77.

I don't have any updates on this at the moment, but my best guess is that it's related to some kind of rate limiting being done by Facebook.
